# Generated by Django 4.1.1 on 2022-09-22 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0003_alter_category_options_alter_women_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='two.category', verbose_name='Катеогория'),
        ),
    ]
